# Generated by Django 3.2.8 on 2022-07-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='conetnt',
            new_name='content',
        ),
    ]
